# Generated by Django 5.0.14 on 2025-12-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["-updated_at"], name="notes_note_updated_79da70_idx"),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["title"], name="notes_note_title_876fe7_idx"),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["created_at"], name="notes_note_created_067654_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name"], name="notes_tag_name_fd9bb0_idx"),
        ),
    ]
